### ISSUE TITLE
Dark theme for settings page

### ISSUE THREAD

**Issue by bbhtt** [alextrv/enhanced-h264ify#21]
![image](https://user-images.githubusercontent.com/62639087/177462354-9c07e97e-23db-4ea8-90ea-cb70a3219cb2.png)

Would be nice to have this page dark themed based on browser/system theme.

browser_style won't work in Firefox due to https://bugzilla.mozilla.org/show_bug.cgi?id=1593355

**Comment by alextrv** [comment]
Implemented in version 2.2.0
