### ISSUE TITLE
AVC1 Codec making it through

### ISSUE THREAD

**Issue by SCdF** [alextrv/enhanced-h264ify#3]
Noted against the original  here: https://github.com/erkserkserks/h264ify/issues/75

This also occurs in this fork.

**Comment by gwarser** [comment]
`avc1` == `h264` - all is working fine.

AV1 is reported by YT as `av01`.

**Comment by SCdF** [comment]
Cool, thanks for the info. I was suspicious as I wasn't able to render 720p24 YT content without it dropping frames so this seemed a likely culprit, but I guess it's something else
