### ISSUE TITLE
Disable Loudness Normalization must be disabled and re-enabled.

### ISSUE THREAD

**Issue by Kafu-Yukimura** [alextrv/enhanced-h264ify#7]
If you change your account or don't play YouTube for a long time, Disable Loudness Normalization will be disabled.
This can be fixed by temporarily must be disabled and re-enabled.

**Comment by mara004** [comment]
Confirmed.
I found that sometimes it YouTube also needs a hard refresh (<kbd>Ctrl</kbd>+<kbd>F5</kbd>). I suspect this might be if YouTube is opened when the extension hasn't fully loaded yet or something.
